version: "3.9"

services:
  productservice:
    container_name: "thirumathikart_productservice"
    image: "thirumathikart_productservice"
    build:
      context: .
      target: ${TARGET}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${RPC_PORT}:${RPC_PORT}
    volumes:
      - .:/app
      - ./product_images:/product_images

  productdb:
    container_name: "thirumathikart_productdb"
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    command: -p ${DB_PORT}
    volumes:
      - ./pg_db:/data/postgres

networks: 
  default: 
    external: 
      name: thirumathikart_network
